# Setup
title:        ใบไม้พระจันทร์
tagline:      Mom's catering service
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       SP
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
